backend:
  name: git-gateway
  branch: master
media_folder: 'public/images'
public_folder: '/images'
collections:
  - name: 'post' # Used in routes, e.g., /admin/collections/blog
    label: 'Post' # Used in the UI
    folder: 'src/pages/posts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: '../../layouts/Layout.astro',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Rating (scale of 1-5)', name: 'rating', widget: 'number' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'testimonials'
    label: 'Testimonials'
    widget: 'list'
    summary: '{{fields.quote}} - {{fields.author.name}}'
    fields:
      - {
          label: Quote,
          name: quote,
          widget: string,
          default: 'Everything is awesome!',
        }
      - label: Author
        name: author
        widget: object
        fields:
          - { label: Name, name: name, widget: string, default: 'Nobody' }
          - {
              label: Avatar,
              name: avatar,
              widget: image,
              default: '/images/nobody.jpg',
            }
